name: Run Tests

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false  # Run tests in CI mode
